import type { Pos } from "./token.ts";
import type {
    AssignStmt, BinOp, Decl, Expr, Item, LValue, PlmType, Proc, Program, Stmt,
} from "./ast.ts";
import type { Resolution, Sym } from "./sema.ts";

export type CodegenOptions = {
    origin?: number;
    stack?: number;
};

export class CodegenError extends Error {
    constructor(message: string, readonly pos: Pos) {
        super(`${pos.line}:${pos.col}: ${message}`);
    }
}

export function generate(program: Program, res: Resolution, opts: CodegenOptions = {}): string {
    const cg = new Codegen(program, res, opts);
    return cg.run();
}

class Codegen {
    private out: string[] = [];
    private labelCounter = 0;
    private procs: Proc[] = [];
    private topDecls: Decl[] = [];
    private currentProc: Proc | null = null;

    constructor(
        private readonly program: Program,
        private readonly res: Resolution,
        private readonly opts: CodegenOptions,
    ) {}

    run(): string {
        const origin = this.opts.origin ?? 0x0100;
        this.line(`; generated by plm-80`);
        this.emitAbsoluteEqus();
        this.line(`    org  ${hex16(origin)}`);
        this.line(`start:`);
        if (this.opts.stack !== undefined) this.line(`    lxi  sp, ${hex16(this.opts.stack)}`);

        for (const item of this.program.items) {
            if (item.kind === "decl") this.topDecls.push(item);
            else if (item.kind === "proc") this.procs.push(item);
            else this.emitStmt(item);
        }
        this.line(`    hlt`);

        for (const proc of this.procs) {
            if (proc.at !== undefined) continue;
            this.blank();
            this.emitProc(proc);
        }

        this.blank();
        this.emitData();
        this.line(`    end`);
        return this.out.join("\n") + "\n";
    }

    private emitAbsoluteEqus(): void {
        const equs: { label: string; addr: number }[] = [];
        for (const item of this.program.items) {
            if (item.kind === "decl" && item.at !== undefined) {
                equs.push({ label: dataLabel(item.name), addr: item.at });
            } else if (item.kind === "proc" && item.at !== undefined) {
                equs.push({ label: procLabel(item.name), addr: item.at });
            }
        }
        if (equs.length === 0) return;
        for (const e of equs) this.line(`${e.label} equ ${hex16(e.addr)}`);
        this.blank();
    }

    private emitProc(proc: Proc): void {
        this.currentProc = proc;
        this.line(`${procLabel(proc.name)}:`);
        for (const item of proc.body) {
            if (item.kind === "decl" || item.kind === "proc") continue;
            this.emitStmt(item);
        }
        if (!this.lastLineIsRet()) this.line(`    ret`);
        this.currentProc = null;
    }

    private lastLineIsRet(): boolean {
        for (let i = this.out.length - 1; i >= 0; i--) {
            const s = this.out[i]!.trim();
            if (s === "") continue;
            return s === "ret";
        }
        return false;
    }

    private emitData(): void {
        this.line(`; --- data ---`);
        const seen = new Set<string>();
        const emitDecl = (d: Decl, labelName: string): void => {
            if (seen.has(labelName)) return;
            seen.add(labelName);
            if (d.at !== undefined) return;
            const t = d.type;
            if (t.kind === "byte") {
                if (d.initial) {
                    this.line(`${labelName}: db ${this.constByte(d.initial[0]!, d.pos)}`);
                } else {
                    this.line(`${labelName}: ds 1`);
                }
            } else if (t.kind === "word" || t.kind === "address") {
                if (d.initial) {
                    this.line(`${labelName}: dw ${this.constWord(d.initial[0]!, d.pos)}`);
                } else {
                    this.line(`${labelName}: ds 2`);
                }
            } else {
                const unit = t.element === "byte" ? 1 : 2;
                if (d.initial) {
                    if (unit === 1) {
                        const parts: string[] = [];
                        let used = 0;
                        for (const e of d.initial) {
                            if (e.kind === "str") {
                                if (e.value.includes('"')) {
                                    throw new CodegenError(`string INITIAL containing '"' is not yet supported`, e.pos);
                                }
                                parts.push(`"${e.value}"`);
                                used += e.value.length;
                            } else {
                                parts.push(this.constByte(e, d.pos));
                                used += 1;
                            }
                        }
                        this.line(`${labelName}: db ${parts.join(", ")}`);
                        const pad = t.size - used;
                        if (pad > 0) this.line(`    ds ${pad}`);
                    } else {
                        const parts = d.initial.map((e) => this.constWord(e, d.pos));
                        this.line(`${labelName}: dw ${parts.join(", ")}`);
                        const pad = t.size - d.initial.length;
                        if (pad > 0) this.line(`    ds ${pad * 2}`);
                    }
                } else {
                    this.line(`${labelName}: ds ${t.size * unit}`);
                }
            }
        };

        for (const d of this.topDecls) emitDecl(d, dataLabel(d.name));
        for (const proc of this.procs) {
            if (proc.regs) continue;
            for (const item of proc.body) {
                if (item.kind !== "decl") continue;
                emitDecl(item, localLabel(proc.name, item.name));
            }
        }
    }

    private constByte(e: Expr, where: Pos): string {
        if (e.kind !== "num") throw new CodegenError("INITIAL must be a numeric literal in v0", where);
        if (e.value < 0 || e.value > 0xff) throw new CodegenError(`byte literal out of range: ${e.value}`, e.pos);
        return hex8(e.value);
    }
    private constWord(e: Expr, where: Pos): string {
        if (e.kind !== "num") throw new CodegenError("INITIAL must be a numeric literal in v0", where);
        if (e.value < 0 || e.value > 0xffff) throw new CodegenError(`word literal out of range: ${e.value}`, e.pos);
        return hex16(e.value);
    }

    // -------- statements --------

    private emitStmt(s: Stmt): void {
        switch (s.kind) {
            case "null": return;
            case "label": this.line(`${userLabel(s.name)}:`); return;
            case "assign": this.emitAssign(s); return;
            case "if": this.emitIf(s); return;
            case "do": for (const it of s.body) {
                if (it.kind === "decl" || it.kind === "proc") continue;
                this.emitStmt(it);
            } return;
            case "while": this.emitWhile(s); return;
            case "call": this.emitCall(s.name, s.args, s.pos, false); return;
            case "return":
                if (s.value) this.evalExpr(s.value, this.procReturnType());
                this.line(`    ret`);
                return;
            case "goto": this.line(`    jmp  ${userLabel(s.label)}`); return;
        }
    }

    private emitAssign(s: AssignStmt): void {
        const vType = this.assignTargetType(s.targets[0]!);
        this.evalExpr(s.value, vType);
        for (let i = 0; i < s.targets.length; i++) {
            const t = s.targets[i]!;
            if (i < s.targets.length - 1) {
                if (vType === "word") this.line(`    push h`);
                else this.line(`    push psw`);
            }
            this.storeToLValue(t, vType);
            if (i < s.targets.length - 1) {
                if (vType === "word") this.line(`    pop  h`);
                else this.line(`    pop  psw`);
            }
        }
    }

    private assignTargetType(t: LValue): "byte" | "word" {
        const sym = this.res.symOf.get(t);
        if (!sym || (sym.kind !== "var" && sym.kind !== "param")) {
            throw new CodegenError(`cannot resolve assignment target '${t.name}'`, t.pos);
        }
        const decl = sym.decl;
        const type = t.kind === "index"
            ? (decl.type.kind === "array" ? decl.type.element : decl.type.kind)
            : decl.type.kind;
        if (type === "byte") return "byte";
        if (type === "word" || type === "address") return "word";
        throw new CodegenError(`unsupported assignment target type '${type}'`, t.pos);
    }

    private storeToLValue(t: LValue, vType: "byte" | "word"): void {
        const sym = this.res.symOf.get(t)!;
        const label = symLabel(sym);
        if (t.kind === "ref") {
            if (vType === "byte") this.line(`    sta  ${label}`);
            else this.line(`    shld ${label}`);
            return;
        }
        // indexed store
        if (vType === "byte") {
            this.line(`    push psw`);
            this.computeAddr(sym, t.index, 1);
            this.line(`    pop  psw`);
            this.line(`    mov  m, a`);
        } else {
            this.line(`    push h`);
            this.computeAddr(sym, t.index, 2);
            this.line(`    pop  d`);
            this.line(`    mov  m, e`);
            this.line(`    inx  h`);
            this.line(`    mov  m, d`);
        }
    }

    private computeAddr(sym: Sym, index: Expr, unit: number): void {
        if (sym.kind !== "var" && sym.kind !== "param") {
            throw new CodegenError(`'${symName(sym)}' not indexable at runtime`, index.pos);
        }
        if (sym.decl.type.kind !== "array") throw new Error("internal: not an array");
        this.evalExpr(index, "word");
        if (unit === 2) this.line(`    dad  h`);
        this.line(`    lxi  d, ${symLabel(sym)}`);
        this.line(`    dad  d`);
    }

    private emitIf(s: import("./ast.ts").IfStmt): void {
        const elseLabel = this.fresh("else");
        const endLabel = this.fresh("endif");
        this.evalExpr(s.cond, "byte");
        this.line(`    ora  a`);
        this.line(`    jz   ${s.else ? elseLabel : endLabel}`);
        this.emitStmt(s.then);
        if (s.else) {
            this.line(`    jmp  ${endLabel}`);
            this.line(`${elseLabel}:`);
            this.emitStmt(s.else);
        }
        this.line(`${endLabel}:`);
    }

    private emitWhile(s: import("./ast.ts").WhileStmt): void {
        const head = this.fresh("while");
        const end = this.fresh("endw");
        this.line(`${head}:`);
        this.evalExpr(s.cond, "byte");
        this.line(`    ora  a`);
        this.line(`    jz   ${end}`);
        for (const it of s.body) {
            if (it.kind === "decl" || it.kind === "proc") continue;
            this.emitStmt(it);
        }
        this.line(`    jmp  ${head}`);
        this.line(`${end}:`);
    }

    private emitCall(name: string, args: Expr[], pos: Pos, asExpr: boolean): void {
        const sym = this.res.global.lookup(name) ?? this.currentScope()?.lookup(name);
        if (!sym || sym.kind !== "proc") {
            throw new CodegenError(`not a procedure: '${name}'`, pos);
        }
        const proc = sym.proc;
        const regs = proc.regs;
        for (let i = 0; i < args.length; i++) {
            const pType = sym.sig.params[i] === "byte" ? "byte" : "word";
            this.evalExpr(args[i]!, pType);
            if (regs) {
                this.moveToReg(pType, regs[i]!, pos);
            } else {
                const paramName = proc.params[i]!;
                const paramSym = this.res.scopeOf.get(proc)!.lookupLocal(paramName);
                if (!paramSym || (paramSym.kind !== "param" && paramSym.kind !== "var")) {
                    throw new CodegenError(`cannot resolve param '${paramName}' of '${name}'`, pos);
                }
                const slot = symLabel(paramSym);
                if (pType === "byte") this.line(`    sta  ${slot}`);
                else this.line(`    shld ${slot}`);
            }
        }
        this.line(`    call ${procLabel(name)}`);
        if (!asExpr) {
            // result discarded if any
        }
    }

    private moveToReg(width: "byte" | "word", reg: string, pos: Pos): void {
        if (width === "byte") {
            switch (reg) {
                case "A": return;
                case "B": this.line(`    mov  b, a`); return;
                case "C": this.line(`    mov  c, a`); return;
                case "D": this.line(`    mov  d, a`); return;
                case "E": this.line(`    mov  e, a`); return;
                case "H": this.line(`    mov  h, a`); return;
                case "L": this.line(`    mov  l, a`); return;
                default: throw new CodegenError(`internal: bad byte reg '${reg}'`, pos);
            }
        } else {
            switch (reg) {
                case "HL": return;
                case "DE": this.line(`    xchg`); return;
                case "BC":
                    this.line(`    mov  b, h`);
                    this.line(`    mov  c, l`);
                    return;
                default: throw new CodegenError(`internal: bad word reg '${reg}'`, pos);
            }
        }
    }

    private currentScope() {
        if (!this.currentProc) return this.res.global;
        return this.res.scopeOf.get(this.currentProc) ?? this.res.global;
    }

    private procReturnType(): "byte" | "word" {
        const rt = this.currentProc?.returnType;
        if (rt === "word" || rt === "address") return "word";
        return "byte";
    }

    // -------- expressions --------
    // Result kind: "byte" -> in A; "word" -> in HL.
    private evalExpr(e: Expr, want: "byte" | "word"): void {
        switch (e.kind) {
            case "num":
                if (want === "byte") {
                    if (e.value < 0 || e.value > 0xff) throw new CodegenError(`byte literal out of range: ${e.value}`, e.pos);
                    this.line(`    mvi  a, ${hex8(e.value)}`);
                } else {
                    this.line(`    lxi  h, ${hex16(e.value & 0xffff)}`);
                }
                return;
            case "ref": {
                const sym = this.res.symOf.get(e);
                if (!sym) throw new CodegenError(`unresolved ref '${e.name}'`, e.pos);
                if (sym.kind === "proc") {
                    this.emitCall(e.name, [], e.pos, true);
                    if (want === "word" && sym.sig.return === "byte") this.byteToWord();
                    if (want === "byte" && (sym.sig.return === "word" || sym.sig.return === "address")) this.wordToByte();
                    return;
                }
                if (sym.kind !== "var" && sym.kind !== "param") {
                    throw new CodegenError(`'${e.name}' not readable as value`, e.pos);
                }
                const t = sym.decl.type;
                if (t.kind === "array") throw new CodegenError(`cannot read whole array '${e.name}'`, e.pos);
                const label = symLabel(sym);
                if (t.kind === "byte") {
                    this.line(`    lda  ${label}`);
                    if (want === "word") this.byteToWord();
                } else {
                    this.line(`    lhld ${label}`);
                    if (want === "byte") this.wordToByte();
                }
                return;
            }
            case "index": {
                const sym = this.res.symOf.get(e);
                if (!sym || (sym.kind !== "var" && sym.kind !== "param")) {
                    throw new CodegenError(`cannot index '${e.name}'`, e.pos);
                }
                if (sym.decl.type.kind !== "array") throw new CodegenError(`'${e.name}' is not an array`, e.pos);
                const unit = sym.decl.type.element === "byte" ? 1 : 2;
                this.computeAddr(sym, e.index, unit);
                if (unit === 1) {
                    this.line(`    mov  a, m`);
                    if (want === "word") this.byteToWord();
                } else {
                    this.line(`    mov  e, m`);
                    this.line(`    inx  h`);
                    this.line(`    mov  d, m`);
                    this.line(`    xchg`);
                    if (want === "byte") this.wordToByte();
                }
                return;
            }
            case "call": {
                const sym = this.res.symOf.get(e);
                if (!sym) throw new CodegenError(`unresolved '${e.name}'`, e.pos);
                if (sym.kind === "var" || sym.kind === "param") {
                    // array index masquerading as call
                    if (sym.decl.type.kind !== "array") throw new CodegenError(`'${e.name}' is not indexable`, e.pos);
                    const unit = sym.decl.type.element === "byte" ? 1 : 2;
                    this.computeAddr(sym, e.args[0]!, unit);
                    if (unit === 1) {
                        this.line(`    mov  a, m`);
                        if (want === "word") this.byteToWord();
                    } else {
                        this.line(`    mov  e, m`);
                        this.line(`    inx  h`);
                        this.line(`    mov  d, m`);
                        this.line(`    xchg`);
                        if (want === "byte") this.wordToByte();
                    }
                    return;
                }
                if (sym.kind !== "proc") throw new CodegenError(`'${e.name}' is not callable`, e.pos);
                this.emitCall(e.name, e.args, e.pos, true);
                const ret = sym.sig.return;
                if (want === "word" && ret === "byte") this.byteToWord();
                if (want === "byte" && (ret === "word" || ret === "address")) this.wordToByte();
                return;
            }
            case "addrOf": {
                const sym = this.res.symOf.get(e);
                if (!sym) throw new CodegenError(`unresolved addrOf '${e.name}'`, e.pos);
                const label = symLabel(sym);
                this.line(`    lxi  h, ${label}`);
                if (want === "byte") this.wordToByte();
                return;
            }
            case "un":
                this.evalExpr(e.arg, want);
                if (e.op === "+") return;
                if (e.op === "-") {
                    if (want === "byte") { this.line(`    cma`); this.line(`    inr  a`); }
                    else {
                        this.line(`    mov  a, l`); this.line(`    cma`); this.line(`    mov  l, a`);
                        this.line(`    mov  a, h`); this.line(`    cma`); this.line(`    mov  h, a`);
                        this.line(`    inx  h`);
                    }
                    return;
                }
                if (e.op === "NOT") {
                    if (want === "byte") this.line(`    cma`);
                    else {
                        this.line(`    mov  a, l`); this.line(`    cma`); this.line(`    mov  l, a`);
                        this.line(`    mov  a, h`); this.line(`    cma`); this.line(`    mov  h, a`);
                    }
                    return;
                }
                return;
            case "bin":
                this.emitBinary(e.op, e.lhs, e.rhs, want, e.pos);
                return;
            case "str":
                throw new CodegenError(`string expressions not supported in v0`, e.pos);
        }
    }

    private emitBinary(op: BinOp, lhs: Expr, rhs: Expr, want: "byte" | "word", pos: Pos): void {
        const isRel = op === "=" || op === "<>" || op === "<" || op === ">" || op === "<=" || op === ">=";
        const operandType: "byte" | "word" = isRel
            ? this.widerOperandType(lhs, rhs)
            : want;

        if (isRel) {
            this.emitCompare(op, lhs, rhs, operandType, pos);
            if (want === "word") this.byteToWord();
            return;
        }
        this.evalExpr(lhs, operandType);
        if (operandType === "byte") this.line(`    push psw`);
        else this.line(`    push h`);
        this.evalExpr(rhs, operandType);
        if (operandType === "byte") {
            this.line(`    mov  b, a`);
            this.line(`    pop  psw`);
            switch (op) {
                case "+": this.line(`    add  b`); break;
                case "-": this.line(`    sub  b`); break;
                case "AND": this.line(`    ana  b`); break;
                case "OR":  this.line(`    ora  b`); break;
                case "XOR": this.line(`    xra  b`); break;
                default: throw new CodegenError(`operator '${op}' not yet implemented for BYTE`, pos);
            }
        } else {
            this.line(`    xchg`);         // HL(rhs) -> DE
            this.line(`    pop  h`);        // lhs -> HL
            switch (op) {
                case "+": this.line(`    dad  d`); break;
                case "-":
                    this.line(`    mov  a, l`);
                    this.line(`    sub  e`);
                    this.line(`    mov  l, a`);
                    this.line(`    mov  a, h`);
                    this.line(`    sbb  d`);
                    this.line(`    mov  h, a`);
                    break;
                case "AND": this.emitWordBitwise("ana"); break;
                case "OR":  this.emitWordBitwise("ora"); break;
                case "XOR": this.emitWordBitwise("xra"); break;
                default: throw new CodegenError(`operator '${op}' not yet implemented for WORD`, pos);
            }
        }
    }

    private emitWordBitwise(mne: string): void {
        this.line(`    mov  a, l`);
        this.line(`    ${mne}  e`);
        this.line(`    mov  l, a`);
        this.line(`    mov  a, h`);
        this.line(`    ${mne}  d`);
        this.line(`    mov  h, a`);
    }

    private emitCompare(op: BinOp, lhs: Expr, rhs: Expr, t: "byte" | "word", pos: Pos): void {
        let left = lhs, right = rhs, normOp: BinOp = op;
        if (op === ">") { left = rhs; right = lhs; normOp = "<"; }
        else if (op === "<=") { left = rhs; right = lhs; normOp = ">="; }

        this.evalExpr(left, t);
        if (t === "byte") this.line(`    push psw`);
        else this.line(`    push h`);
        this.evalExpr(right, t);
        const tt = this.fresh("ctrue");
        const end = this.fresh("cend");
        if (t === "byte") {
            this.line(`    mov  b, a`);
            this.line(`    pop  psw`);
            this.line(`    cmp  b`);
        } else {
            this.line(`    xchg`);
            this.line(`    pop  h`);
            this.line(`    mov  a, l`);
            this.line(`    sub  e`);
            this.line(`    mov  a, h`);
            this.line(`    sbb  d`);
        }
        let jmpTrue: string;
        switch (normOp) {
            case "=":  jmpTrue = "jz";  break;
            case "<>": jmpTrue = "jnz"; break;
            case "<":  jmpTrue = "jc";  break;
            case ">=": jmpTrue = "jnc"; break;
            default: throw new CodegenError(`unknown relational op '${op}'`, pos);
        }
        this.line(`    ${jmpTrue}   ${tt}`);
        this.line(`    xra  a`);
        this.line(`    jmp  ${end}`);
        this.line(`${tt}:`);
        this.line(`    mvi  a, 0FFh`);
        this.line(`${end}:`);
    }

    private widerOperandType(a: Expr, b: Expr): "byte" | "word" {
        const ta = this.res.typeOf.get(a);
        const tb = this.res.typeOf.get(b);
        const isWord = (t?: { kind: string }) => t?.kind === "word" || t?.kind === "address";
        return isWord(ta) || isWord(tb) ? "word" : "byte";
    }

    private byteToWord(): void {
        this.line(`    mov  l, a`);
        this.line(`    mvi  h, 0`);
    }
    private wordToByte(): void {
        this.line(`    mov  a, l`);
    }

    // -------- output helpers --------

    private line(s: string): void { this.out.push(s); }
    private blank(): void { this.out.push(""); }
    private fresh(hint: string): string {
        this.labelCounter++;
        return `L${this.labelCounter}_${hint}`;
    }
}

function hex8(n: number): string {
    const s = (n & 0xff).toString(16).toUpperCase().padStart(2, "0");
    return (s[0]! >= "A" ? "0" : "") + s + "h";
}
function hex16(n: number): string {
    const s = (n & 0xffff).toString(16).toUpperCase().padStart(4, "0");
    return (s[0]! >= "A" ? "0" : "") + s + "h";
}
function dataLabel(name: string): string { return name.toLowerCase(); }
function localLabel(proc: string, name: string): string { return `${proc.toLowerCase()}_${name.toLowerCase()}`; }
function procLabel(name: string): string { return name.toLowerCase(); }
function userLabel(name: string): string { return name.toLowerCase(); }

function symLabel(sym: Sym): string {
    if (sym.kind === "var") {
        if (sym.storage === "global" || sym.storage === "absolute") return dataLabel(sym.decl.name);
        if (!sym.proc) throw new Error(`local var '${sym.decl.name}' has no owning proc`);
        return localLabel(sym.proc.name, sym.decl.name);
    }
    if (sym.kind === "param") return localLabel(sym.proc.name, sym.decl.name);
    if (sym.kind === "proc") return procLabel(sym.proc.name);
    throw new Error(`no asm label for symbol kind '${sym.kind}'`);
}

function symName(sym: Sym): string {
    if (sym.kind === "var" || sym.kind === "param") return sym.decl.name;
    if (sym.kind === "proc") return sym.proc.name;
    return "<label>";
}
